global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alerts.rules


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alert-manager:9093"

            
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
      

  - job_name: some-service
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - "some-service:80"
        labels:
          versao: "1.0"
          env: "dev"