global:
  slack_api_url: SLACK_API_URL

route:
  receiver: Default
  group_by: ["alertname"]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: "AlertRegisterService"
      match:
        team: developers

    - receiver: "AlertListService"
      match:
        team: developersc

    - receiver: slack-notifications
      match: 
        severity: 'critical'

receivers:
  - name: Default
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"

  - name: AlertRegisterService
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"

  - name: AlertListService
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"

  - name: "slack-notifications"
    slack_configs:
      - channel: "#alertas-prometheus"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
