services:
  grafana-lgtm:
    image: grafana/otel-lgtm:0.6.0
    container_name: grafana-otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=1000
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true