services:
  entrypoint:
    container_name: entrypoint
    image: api-otel
    build:
      context: ./ApiOtel
      dockerfile: Dockerfile
    ports:
      - 5280:80
    environment:
      - ASPNETCORE_URLS=http://+:80 
      - OpenTelemetry__ServiceName=entrypoint
      - ASPNETCORE_ENVIRONMENT=Docker
      - Mode=CLIENT
      - Client__Url=http://operational
      - OTEL_METRIC_EXPORT_INTERVAL=500
    mem_limit: 50M
    cpus: 0.25
  
  operational:
    container_name: operational
    image: api-otel    
    ports:
      - 5281:80
    environment:
      - ASPNETCORE_URLS=http://+:80 
      - OpenTelemetry__ServiceName=operational
      - ASPNETCORE_ENVIRONMENT=Docker
      - Mode=CLIENT
      - Client__Url=http://core
      - OTEL_METRIC_EXPORT_INTERVAL=500
    mem_limit: 50M
    cpus: 0.25
    depends_on: 
     - entrypoint
  
  core:
    container_name: core
    image: api-otel    
    ports:
      - 5282:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - OpenTelemetry__ServiceName=core 
      - ASPNETCORE_ENVIRONMENT=Docker
      - Mode=SERVER
      - OTEL_METRIC_EXPORT_INTERVAL=500
    mem_limit: 50M
    cpus: 0.25
    depends_on:
      - operational

  grafana-lgtm:
    image: grafana/otel-lgtm:0.6.0
    container_name: grafana-otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    environment:      
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  request-runner:
    image: leandroalves86/ubuntu-curl
    container_name:  request-runner
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu.Curl
    volumes:
      - ./request.sh:/app/request.sh
    mem_limit: 150M
    cpus: 0.25
    depends_on:
      - entrypoint