groups:
  - name: ErrorOnRegister
    rules:
      - alert: Error on Registering Weatherforecast
        expr: sum(count(rate(register_weatherforecast_failures[1m]))) > 1
        for: 10s
        labels:
          team: developers
          service: "{{ $labels.instance }}"
          method: "POST"
        annotations:
          title: "Alta taxa de Errors"
          description: "O serviço {{ $labels.instance }} está apresentando uma alta taxa de erros"

  - name: ErrorOnList
    rules:
      - alert: Error on Listing Weatherforecast
        expr: sum(count(rate(list_weatherforecast_failures[1m]))) > 1
        for: 10s
        labels:
          team: developers
          service: "{{ $labels.instance }}"
          method: "GET"
        annotations:
          title: "Alta taxa de Errors"
          description: "O serviço {{ $labels.instance }} está apresentando uma alta taxa de erros"

  - name: AllInstances
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 20s
      annotations:
        title: 'Instance {{ $labels.instance }} down'
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 20 seconds.'
      labels:
          severity: 'critical'