global:
route:
  receiver: Default
  group_by: ["alertname"]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: "AlertaDatabase"
      match:
        team: mongodb

    - receiver: "AlertaWebApi"
      match:
        team: webapi

receivers:
  - name: Default
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"

  - name: AlertaDatabase
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"

  - name: AlertaWebApi
    webhook_configs:
      - url: "https://eob86j0vyrtsotn.m.pipedream.net"
